'use client'
import { useState } from 'react'
import type { Player } from '@/lib/types'
import { EmptyState } from '@/components/page-heading'
export function PlayerRoster({ players }: { players: Player[] }) {
  const [search, setSearch] = useState('')
  const [position, setPosition] = useState('')
  const [sort, setSort] = useState('dorsal')
  const positions = [...new Set(players.flatMap((player) => player.positions))].sort()
  const visible = players.filter((player) => `${player.name} ${player.dorsal}`.toLocaleLowerCase('es').includes(search.toLocaleLowerCase('es')) && (!position || player.positions.includes(position))).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name, 'es') : sort === 'goals' ? (b.goals ?? 0) - (a.goals ?? 0) : a.dorsal - b.dorsal)
  return <><div className="surface grid gap-4 sm:grid-cols-[2fr_1fr_1fr] mb-6"><label className="text-xs text-muted-foreground">Buscar jugador<input type="search" className="field mt-2" placeholder="Nombre o dorsal" value={search} onChange={(event) => setSearch(event.target.value)} /></label><label className="text-xs text-muted-foreground">Posición<select className="field mt-2" value={position} onChange={(event) => setPosition(event.target.value)}><option value="">Todas las posiciones</option>{positions.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-xs text-muted-foreground">Ordenar por<select className="field mt-2" value={sort} onChange={(event) => setSort(event.target.value)}><option value="dorsal">Dorsal</option><option value="name">Nombre</option><option value="goals">Goles</option></select></label></div><p className="text-sm text-muted-foreground mb-4" role="status">{visible.length} jugadores activos</p>{visible.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map((player) => <article key={player.id} className="surface"><div className="flex items-start justify-between gap-4"><span className="flex items-center justify-center w-16 h-16 rounded-[22px] bg-secondary font-bold text-2xl text-primary">{player.dorsal}</span><span className="eyebrow !text-[10px] pt-2">ITJAGUARS FC</span></div><h2 className="text-xl mt-5">{player.name}</h2><p className="text-xs text-muted-foreground mt-2 min-h-8">{player.positions.join(' · ') || 'Posición por definir'}</p><dl className="grid grid-cols-2 gap-3 pt-4 border-t mt-4"><div><dt className="text-xs text-muted-foreground">Convocatorias</dt><dd className="text-2xl font-semibold mt-1">{player.callUps}</dd></div><div><dt className="text-xs text-muted-foreground">Goles</dt><dd className="text-2xl font-semibold mt-1">{player.goals}</dd></div></dl></article>)}</div> : <EmptyState>No encontramos jugadores con estos filtros.</EmptyState>}</>
}
